### ISSUE TITLE
2 times $this->basket->sGetBasket()

### ISSUE THREAD

**Issue by h4rvk4** [shopware5/shopware#101]
Hi there,

I'm worndering of this (in engine/Shopware/Controllers/Frontend/Checkout.php):

```
public function getBasket()
{
    $basket = $this->basket->sGetBasket();

    $shippingcosts = $this->getShippingCosts();

    $basket = $this->basket->sGetBasket();

    [...]
}
```

Why calling two times $this->basket->sGetBasket()?
I guess the first call is unnecessary and would save much time when removed.

**Comment by dnoegel** [comment]
Hi  @haruka,

this double calculation is currently needed and is about to be adressed once we refactor our core classes. Removing the double-call might affect your price calculation and is not recommended.
