### ISSUE TITLE
use composer for dependency management

### ISSUE THREAD

**Issue by lsmith77** [shopware5/shopware#11]

**Comment by sthamann** [comment]
Thanks Lucas.

We will reschedule the implementation of composer for dependency management to Shopware 4.1.0

**Comment by bcremer** [comment]
+1 For Composer.

@lsmith77 Do you know about resources / best practices how to maintain patches for composer managed dependencies?

Some of our patches won't be included in upstream projects so we have to apply them right after composer.phar install / update. 

Are there any hooks etc. available to archive this without requiring a separate ant/phing build-script?

**Comment by lsmith77** [comment]
you can always override a remote repo with a specific one inside your composer.json
http://getcomposer.org/doc/05-repositories.md

**Comment by axzx** [comment]
+1 For Composer.

**Comment by bcremer** [comment]
The (post-install-cmd)-[Composer Scripts](http://getcomposer.org/doc/articles/scripts.md) took my attention.
I will take a look if we can maintain our patches without having to maintain a fork of the dependencies.

Composer is definitive on the radar for the 4.1 Release.

**Comment by lennartdiedrich** [comment]
It would be great, if composer comes with the release of version 4.1. This would simplify our development extremely.

**Comment by bcremer** [comment]
Well, I'll do my very best ;)

**Comment by mablae** [comment]
everthing is better with composer (bluetooth) :+1:

**Comment by shredding** [comment]
:+1:

**Comment by ghost** [comment]
There is still no composer support in version 4.1.2 .. when do plan on implementing this?

**Comment by dnoegel** [comment]
Hi @MrMaxon,

as far as I know, this is currently not scheduled for a release. Please vote and comment here, so we can push this a bit :) => http://jira.shopware.de/?ticket=sw-6989

**Comment by dnoegel** [comment]
Hi,

thanks for opening this issue. In order to have all issues at one place, we've decided to move the GitHub issues to our own bug tracker which can be found at http://jira.shopware.de.

Your ticket can be found at the following url:

http://jira.shopware.de/?ticket=sw-6989
