### ISSUE TITLE
move away from *GPL license

### ISSUE THREAD

**Issue by lsmith77** [shopware5/shopware#12]
*GPL licenses are more than a gray area for interpreted languages. not sure if ExtJS is really worth this mess .. also the license interpretation of ExtJS "infecting" server side code is questionable. But with a more decoupled philosophy (http://decoupledcms.org) it should be possible to separate the ExtJS dependency in such a way that there should be no reason to influence your license decision.

**Comment by MarcelSchmaeing** [comment]
Thanks for the advice
