### ISSUE TITLE
Suggest feature branches for pull requests

### ISSUE THREAD

**Issue by BjoernSchotte** [shopware5/shopware#15]
Regarding issue 2: perhaps there was some misunderstanding. The common practice is:

I, as a community member, fork the shopware-4 repository from master. Then I create a _feature/topic branch_ in _my forked repository_, contribute and commit code. If I'm ready to push it to the upstream, I then create a pull request for your master branch.

Please refer to https://help.github.com/articles/using-pull-requests for further details.

**Comment by BjoernSchotte** [comment]
Any news on this?

**Comment by sthamann** [comment]
Hi Bjoern,

genauso ist das ja möglich. Master ist ja immer unser aktueller Trunk, daher müssen aufwendigere Features die per Pull-Request zurückkommen, zuerst in den Feature-Branch - dort durchlaufen die unsere normalen QA-Prozesse und werden dann mit dem übernächsten Minor-Release zurück in den Master gemerged. Kleinere Verbesserungen und Bugfixes kommen direkt in den Master.

**Comment by lennartdiedrich** [comment]
Dadurch nehmt ihr euch natürlich den tollen Github Vorteil, dass man per Klick den Code einfach in den Master mergen kann. Euer vorgehen ist da schon etwas komplizierter.

**Comment by bcremer** [comment]
Hi Björn,

wir haben die Dokumentation mit dem Commit https://github.com/ShopwareAG/shopware-4/commit/c60a409518720788e6de65ba4718a0e618f74f93 auf Feature-Branches umgestellt.

Danke für deinen Beitrag :+1:
