### ISSUE TITLE
REST-API: create/update should return success state / no redirect

### ISSUE THREAD

**Issue by derkra** [shopware5/shopware#16]
Each REST-Controller for post/put (repective create/update) ends with this code:

$this->View()->assign(array('success' => true, 'data' => $data));
$this->Response()->setHeader('Location', $location);

Please remove the last line. Returning the json-response ist a better way for the REST-client to determine if the action was successful.

**Comment by bcremer** [comment]
Hi, thanks for your input.

It's good practise to specify the URI of a newly created resource in the Location response header.

I don't see any drawbacks for including the location header.

**Comment by derkra** [comment]
Hello,

ok, researching on this topic, you are right!
A location header does not alway mean a redirect. The statuscode is ok (200) on success.
