### ISSUE TITLE
Suggest feature branches for pull requests

### ISSUE THREAD

**Issue by BjoernSchotte** [shopware5/shopware#2]
Often it is common usage to suggest people should create feature branches for their feature enhancements and then submit pull requests.

Thus, everything is more in order and a discussion inside the feature branch can take place before accepting and merging it upstream into the master (or whatever) branch on this repo.

Affects README.md

**Comment by sthamann** [comment]
Thanks Björn - we have modified the readme.md and have created a feature branch.
