### ISSUE TITLE
missing s_article_configurator_templates

### ISSUE THREAD

**Issue by cKehres** [shopware5/shopware#21]
Nach einer frischen 4.0.4 Installation fehlt die Tabelle s_article_configurator_templates.

Möchte ich einen Artikel anlegen wird nen Fehler ausgegeben aber der Artikel an sich angelelgt.

Im Frontend gibts dann die Meldung:

Ups! Ein Fehler ist aufgetreten!

Die nachfolgenden Hinweise sollten Ihnen weiterhelfen.
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'shopware_andys-musicshop.s_article_configurator_templates' doesn't exist in Doctrine/DBAL/Connection.php on line 628

**Comment by lennartdiedrich** [comment]
Das kann ich nicht bestätigen. Hast du den neusten installer benutzt? Kann es sein, dass vielleicht noch eine alte `sw4_clean.sql` benutzt wurde?

**Comment by cKehres** [comment]
gerade eben erst gezogen, setup lief ohne fehler durch

**Comment by cKehres** [comment]
gerade gesehen das der pull vorhin schief gelaufen war, vorallem bei der sw4_clean lief was schief, closed, GITHUB hats zerhauen... :)
