### ISSUE TITLE
Versandart wird nicht übersetzt beim Checkout

### ISSUE THREAD

**Issue by StingerMKO** [shopware5/shopware#22]
Beim Checkout wird trotz Übersetzung die Versandart nicht auf z.B. Englisch angezeigt. Die Zahlungsart und das Lieferland werden korrekt übersetzt.

Getestet bei einer frischen Shopware 4.0.4 Installation.

Dies scheint ein Bug zu sein, deshalb denke ich, dass mir der öffentliche Forumssupport nicht helfen kann.

**Comment by MarcelSchmaeing** [comment]
Hi,

vielen Dank für dein Feedback.
Dieses Verhalten werden wir voraussichtlich bereits in der 4.0.5 lösen.

Grüße,

marcel
