### ISSUE TITLE
99 papercuts project 404 not found

### ISSUE THREAD

**Issue by SimonBaeumer** [shopware5/shopware#2532]
Hey all!
The 99 papercuts link is broken. I've linked it as a reference for an internal 99 papercuts project as a success reference.
Is it possible to recover it @mitelg? It seems to be lost with the repository migration.

Link: https://github.com/shopware5/shopware/projects/1

Best,
Simon

**Comment by mitelg** [comment]
Hey Simon :wave: 

sorry, it is not planned to use the "project" functionality, so we disabled it for now. Although it might change in the future. 

How about linking to this search instead? https://github.com/shopware5/shopware/pulls?q=is%3Apr+is%3Aclosed+%5Bpapercut%5D

Best regards from Schöppingen
Telgi

**Comment by SimonBaeumer** [comment]
@mitelg Hey Michael, the link is perfect, thank you!
