### ISSUE TITLE
merchant registration

### ISSUE THREAD

**Issue by i3rinkmann** [shopware5/shopware#2572]
### Description

with the update to version 5.7.18 the merhcent registration form/url is broken. Previewsly you could enter the url /registerFC/index/sValidation/H to direktly get to the merchant registration form.

### PHP Version

7.4.33

### Shopware Version

5.7.18

### How to reproduce

call the URL http://your.shop.com/registerFC/index/sValidation/H

### Expected behaviour

You see the merchent registration form

### Actual behaviour

Fatal error: Uncaught Error: Call to undefined function content_64d4debcef7388_38107991() in /www/htdocs/myuser/your.shop.com/var/cache/production_202306271137/templates/frontend_Elsentheme_de_DE_1_secure/10/fd/14/10fd14443b85c4316aea9d87e9f496a21451a654.snippet.form.js.php:366 Stack trace: #0 /www/htdocs/myuser/your.shop.com/engine/Library/Smarty/sysplugins/smarty_internal_templatebase.php(180): content_64d4debd1fbd94_17655167(Object(Enlight_Template_Default)) #1 /www/htdocs/myuser/your.shop.com/engine/Library/Enlight/View/Default.php(286): Smarty_Internal_TemplateBase->fetch() #2 /www/htdocs/myuser/your.shop.com/engine/Library/Enlight/Controller/Plugins/ViewRenderer/Bootstrap.php(180): Enlight_View_Default->render(Object(Enlight_Template_Default)) #3 /www/htdocs/myuser/your.shop.com/engine/Library/Enlight/Controller/Plugins/ViewRenderer/Bootstrap.php(207): Enlight_Controller_Plugins_ViewRenderer_Bootstrap->renderTemplate(Object(Enlight_Template_Default)) #4 /www/htdocs/myuser/sh in /www/htdocs/myuser/your.shop.com/var/cache/production_202306271137/templates/frontend_Elsentheme_de_DE_1_secure/10/fd/14/10fd14443b85c4316aea9d87e9f496a21451a654.snippet.form.js.php on line 366

**Comment by mitelg** [comment]
hey @i3rinkmann 

I cannot reproduce this issue on my machine. can you reproduce this with the default shopware theme? because your error trace indicates that you are using a custom theme.

**Comment by i3rinkmann** [comment]
hey @mitelg 
It seems the problem is not with the template but with the customer groups... it seems the customergroup "Händler" with the short key "H" got deleted. We are unsure how or why it got deleted since there is no backend-log that indicates someone deleting the group.

But i would argue the /egisterFC/index/sValidation endpoint shopuld handle missing groups better then throw such a cryptic error.

I think the issue can be closed since its not a bug but an error handling problem.

**Comment by mitelg** [comment]
hey @i3rinkmann 

thanks for the clarification :+1: 

If this is because of a missing customer group, then I totally agree on you, that this could be improved. If you like, open another issue for that, with a workflow describing how the error occurs. Maybe someone is going to fix that problem.
