### ISSUE TITLE
Unable to Connect to ssl://raw.githubusercontent.com:443. Error #110: Connection timed out

### ISSUE THREAD

**Issue by dxDennis** [shopware5/shopware#2576]
### Description

Since 5.7 checkUpdate in
engine/Shopware/Plugins/Default/Backend/SwagUpdate/Components/UpdateCheck.php
needs much longer than the given timeout of 5sec. If I increase it to 30 seconds everything behaves like it should.

Where can I set this for good since my hacked 30sec will disapear as soon es the next Update will overwrite this.

Thanks

### PHP Version

8.2

### Shopware Version

5.8

### How to reproduce

Shopware Backend-> click on help questionmark and select "Softwareaktualisierung".

If default time_out for Zend_Adapter 5sec. is too short for your ISP you will get an error: Unable to Connect to ssl://raw.githubusercontent.com:443. Error #110: Connection timed out

### Expected behaviour

Successful call of the UpdateChecker, wether to update the Shopsoftware or not.

### Actual behaviour

It runs into an error when time out seconds was too short. 
would be perfect to set this for good in config.php

**Comment by mitelg** [comment]
hey @dxDennis 

the timeout is defined within the service definition of the client: https://github.com/shopware5/shopware/blob/v5.7.18/engine/Shopware/Components/DependencyInjection/services.xml#L49-L54

It should be possible to override this definition: https://symfony.com/doc/4.4/bundles/override.html#services-configuration

Best regards from Schöppingen
Michael Telgmann
