### ISSUE TITLE
install.sql and snippets.sql are missing 

### ISSUE THREAD

**Issue by Myrmod** [shopware5/shopware#2583]
### Description

Well, the file `/recovery/install/data/sql/install.sql` is missing and it's not mentioned anywhere, where it can be found or why it is missing in the first place.

### PHP Version

7.4

### Shopware Version

5.7

### How to reproduce

Try to install shopware

### Expected behaviour

All for the installation required files are provided or linked

### Actual behaviour

Error is shows:

```
 
Slim Application Error

The application could not run because of the following error:

Details

Type: ErrorException

Code: 2

Message: fopen(/var/www/html/shopware/recovery/install/src/../data/sql/install.sql): failed to open stream: No such file or directory

File: /var/www/html/shopware/recovery/common/src/DumpIterator.php

Line: 61

Trace


 
#0 [internal function]: Slim\Slim::handleErrors(2, 'fopen(/var/www/...', '/var/www/html/s...', 61, Array)#1 /var/www/html/shopware/recovery/common/src/DumpIterator.php(61): fopen('/var/www/html/s...', 'rb')#2 /var/www/html/shopware/recovery/install/src/ContainerProvider.php(101): Shopware\Recovery\Common\DumpIterator->__construct('/var/www/html/s...')#3 /var/www/html/shopware/recovery/common/vendor/pimple/pimple/src/Pimple/Container.php(109): Shopware\Recovery\Install\ContainerProvider->Shopware\Recovery\Install\{closure}(Object(Pimple\Container))#4 /var/www/html/shopware/recovery/install/src/app.php(538): Pimple\Container->offsetGet('database.dump_i...')#5 [internal function]: {closure}()#6 /var/www/html/shopware/recovery/common/vendor/slim/slim/Slim/Route.php(462): call_user_func_array(Object(Closure), Array)#7 /var/www/html/shopware/recovery/common/vendor/slim/slim/Slim/Slim.php(1326): Slim\Route->dispatch()#8 /var/www/html/shopware/recovery/common/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call()#9 /var/www/html/shopware/recovery/common/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()#10 /var/www/html/shopware/recovery/common/vendor/slim/slim/Slim/Middleware/PrettyExceptions.php(67): Slim\Middleware\MethodOverride->call()#11 /var/www/html/shopware/recovery/common/vendor/slim/slim/Slim/Slim.php(1271): Slim\Middleware\PrettyExceptions->call()#12 /var/www/html/shopware/recovery/install/index.php(75): Slim\Slim->run()

#13 {main}
```

**Comment by mitelg** [comment]
Hi @Myrmod 

could you elaborate a bit? 
Did you download a zip file? where did you downloaded it? 
did you something else, like building the current dev branch? 
Please give us more information :slightly_smiling_face:

**Comment by Myrmod** [comment]
> 

Thank you for the quick response. I cloned the repository `git clone --branch=5.7 https://github.com/shopware5/shopware` and set up the enironment using `ddev`, now I am in the installer and I can't proceed, since files that the installer is requesting, are missing. I found the same issue on another side: https://forum.shopware.com/t/slim-application-error-installing-shop-ware-5-3/47641/4

**Comment by mitelg** [comment]
please follow the installation instructions from the [readme file](https://github.com/shopware5/shopware?tab=readme-ov-file#installation-via-git) if you are installing Shopware via git

The web installer could only be used, if a package is build. during this process the SQL file is created, that is missing in your attempt.

**Comment by Myrmod** [comment]
Seems like I didn't call the make command properly, now I am able to get into the backend:

- `git clone --branch=5.7 https://github.com/shopware5/shopware shopware5 && cd shopware5`
- `chmod -R 755 custom/plugins`
- `ddev config --project-type=php --database=mysql:5.7 --webserver-type=apache-fpm --php-version 7.4` 
- `cp .env.dist .env`
- change the `.env` content to 
	```
	DB_USER=db
	DB_PASSWORD=db
	DB_HOST=db
	DB_NAME=db
	DB_PORT=3306
	SW_HOST=shopware5.ddev.site
	SW_BASE_PATH=
	SELENIUM_HOST=selenium
	ELASTICSEARCH_HOST=elasticsearch
	SMTP_HOST=smtp
	```
- enter container to install make `docker exec -u root -it ddev-shopware5-web bash`
- `apt-get update && apt-get install make`, exit container
- `ddev exec make init`
- `wget -O test_images.zip http://releases.shopware.com/test_images_since_5.1.zip`
- `unzip test_images.zip`, use option `A`
- `ddev start`
- navigate to https://shopware5.ddev.site/backend/ and login username: `demo`, password: `demo`

That's what I did so far. Currently I am not able to open up the frontend. I might be missing some frontend related data or I am missing some configuration. 

Thank you for the help!

**Comment by aragon999** [comment]
Change `SW_HOST` from `localhost` to `shopware5.ddev.site`. If you have already installed it, check the URL configuration of the shop from the administration basic settings.
