### ISSUE TITLE
install.sql & snippt.sql file missing in /data/sql/install.sql

### ISSUE THREAD

**Issue by saeedashraf1991** [shopware5/shopware#2617]
### Description

I am at localhost (apache 2 installed) Ubunut 22 OS. 
I have downloaded Shopware5 from the git repo https://github.com/shopware5/shopware/releases.
At URL: http://localhost/shopware5/recovery/install/index.php/database-import/ its displaying an error message. 

Error
Received an error message.
URL: importDatabase?offset=0&totalCount=0
Message: Internal Server Error

Please try to fix this error and restart the update.
Response
Slim Application Error
The application could not run because of the following error:

Details
Type: ErrorException
Code: 2
Message: fopen(/var/www/html/shopware5/recovery/install/src/../data/sql/install.sql): Failed to open stream: No such file or directory
File: /var/www/html/shopware5/recovery/common/src/DumpIterator.php
Line: 62

### PHP Version

7.4

### Shopware Version

5

### How to reproduce

Download Shopware5 from git repo https://github.com/shopware5/shopware/releases. Once you will unzip & try to install, the error will be. 
 fopen(/var/www/html/shopware5/recovery/install/src/../data/sql/install.sql): Failed to open stream: No such file or directory

### Expected behaviour

If are configuration requirements are met, Shopware5 must be installed happily

### Actual behaviour

It's showing an error in the installation of the file not found.

**Comment by mitelg** [comment]
hey @saeedashraf1991 

which version and which ZIP file did you exactly downloaded?

**Comment by saeedashraf1991** [comment]
Hi @mitelg, 
its [v5.7.19](https://github.com/shopware5/shopware/releases/tag/v5.7.19) 
& [Release 5.7.18](https://github.com/shopware5/shopware/releases/tag/v5.7.18) 
Facing issues on both.

**Comment by mitelg** [comment]
I just downloaded `install_e75856b1d446ab80746b4db216e11875c4f8159a.zip` for `5.7.19` and the SQL files are there :thinking: 
![image](https://github.com/shopware5/shopware/assets/6985627/73cfcc95-9f05-4455-9f51-85239c3d471c)

same for `5.7.18` (`install_9438a378537ad6414ab7c6e0083d07efb3f2d101.zip`) 
![image](https://github.com/shopware5/shopware/assets/6985627/26ef7a74-3842-40e0-980d-62dea4768a2d)

**Comment by mitelg** [comment]
hey @saeedashraf1991 

is this still an issue?

**Comment by saeedashraf1991** [comment]
Hi @mitelg 
Thank you for your help, following your above comment. I downloaded **install** zip file & issue is resolved. Previously I was downloading **source code**. 
Thank you mate :)
