### ISSUE TITLE
How I can fetch Voucher Code in Order details

### ISSUE THREAD

**Issue by saeedashraf1991** [shopware5/shopware#2618]
### Summary

Hi guys, 
I want to fetch the Discount Code applied at checkout in order details. Mainly I am working at checkout/finish.tpl. Can you please advise how to get the Coupon/discount code applied? 

Thank you!

### Basic Example

Like this: 

$discountCode = Shopware()->Db()->fetchAll(
            'SELECT *
         FROM s_order
         WHERE ordernumber = :ordernumber',
            ['ordernumber' => $orderNumber]
        );

**Comment by mitelg** [comment]
hey @saeedashraf1991 

we want to keep the issues for bugfix reports or feature request. 

If you have a question that needs support, please use [Stackoverflow](https://stackoverflow.com/questions/tagged/shopware5), our [community slack](https://slack.shopware.com) (channel #shopware5) or our [community forum](https://forum.shopware.com/c/shopware-5/7).

Thanks for your understanding.
Best regards from Schöppingen
Telgi
