### ISSUE TITLE
“Redeemable vouchers per customer” option does not work correctly 

### ISSUE THREAD

**Issue by vismagine** [shopware5/shopware#2622]
### Description

When a voucher is created with the “Redeemable vouchers per customer” option, the number of redemptions per customer is not counted correctly. The checkVoucherCustomerRestriction method in the BasketHelper class uses the customer's email address to count the number of redemptions, but the table “s_order_details” does not have an “email” column. This causes the method to always return a value of 0 for the number of orders, leading to incorrect results. The method should instead use the “ordernumber” column to count the number of redemptions or use the “s_order” table which has the “email” column.

### PHP Version

8.1

### Shopware Version

5.7.17

### How to reproduce

Reproduction steps:

- Create a general or individual voucher with any value for the Redeemable vouchers per customer option (except 0).
- Put one or more items in the shopping cart and enter the voucher code.
- Complete the order.
- Try entering the same coupon code again.
- Observe that the voucher is still being accepted even though it has already been redeemed. 

### Expected behaviour

Expected Result: The voucher should be rejected if the number of redemptions per customer is equal to or greater than the value of the option. 

### Actual behaviour

Actual result: The voucher is always accepted, regardless of the number of redemptions per customer.

**Comment by mitelg** [comment]
hey @vismagine 

can you show me which "BasketHelper" you are meaning? The one in [our code](https://github.com/shopware5/shopware/blob/v5.7.17/engine/Shopware/Components/Cart/BasketHelper.php) does not have a method `checkVoucherCustomerRestriction`. 

In general I cannot find a method with this name :thinking: 

Could you provide some more information here?

**Comment by mitelg** [comment]
hey @vismagine 

can you elaborate a bit more here? Otherwise I would close the issue :slightly_smiling_face:

**Comment by mitelg** [comment]
Hey @vismagine 

This ise was closed due to inactivity. If this bug is still important to you, feel free to create a new issue with the requested information
