### ISSUE TITLE
Shoppingworld Article Slider: Uncaught TypeError: Cannot read properties of undefined (reading 'hide')

### ISSUE THREAD

**Issue by marcelfinkde** [shopware5/shopware#2628]
### Description

Hi,

when i want to edit an article slider, the popup window is not showing up.

But in the Console these error messages appear

![2024-01-16 21_43_57-Greenshot](https://github.com/shopware5/shopware/assets/45934260/ddd768cf-5586-4e2c-97ec-6ec4aac7eab4)

in the source code for example line 13276 is highlighted with an error message.

![Zwischenablage01](https://github.com/shopware5/shopware/assets/45934260/811babaf-d8b7-4152-8fbb-6fb7331ba9b9)

### PHP Version

7.4.33

### Shopware Version

5.7.17

### How to reproduce

Edit the Article Slider Widget

### Expected behaviour

It has to open the PopUp

### Actual behaviour

Nothing happens

**Comment by mitelg** [comment]
hey @marcelfinkde 

I can not reproduce this on current 5.7 development branch :thinking: 

do you have some plugins installed, that are extending the shopping worlds?

**Comment by marcelfinkde** [comment]
Hi,

yes but I deinstalled them already to test it. 

We run a theme from Themeware but the appeared long time after using the plugins. 

www.funtainment.shop

**Comment by mitelg** [comment]
then it might be some other customization :thinking: 

I am sorry, that I have to say it, but if it is not reproducible in a default setup, it would be hard to fix :wink:

**Comment by mitelg** [comment]
Hey @marcelfinkde 

This issue was closed due to inactivity.
