### ISSUE TITLE
Prozentrabat für Artikel defekt

### ISSUE THREAD

**Issue by HellPat** [shopware5/shopware#30]
im aktuellen master sowie in der 4.04 Rev 6174 kann ich beim Prozentrabatt nichts eintragen.
Auch mit Pfeil hoch/runter ändert sich nichts.

**Comment by dnoegel** [comment]
Hallo,

danke für die Meldung. Ich kann sie so leider gerade nicht nachstellen. Wenn ich eine Preisstaffel anlege und dann beim zweiten Artikel einen prozentualen Wert setze, wird der Preis korrekt berechnet.

Was - falls das so gemeint war - zutrifft, ist, dass man nicht einfach beim ersten Artikel einen Prozentwert eintragen kann und dann der nächste Artikel entsprechend gesetzt wird. Der Prozentwert bezieht sich also immer auf den vorherigen Artikel, weshalb er beim ersten Artikel nicht gesetzt werdne kann.

Kannst du das nochmal testen oder mir eine Anleitung zum Nachstellen geben? Ich kann natürlich auch nicht ausschließen, dass es innerhalb der letzten drei Tage behoben wurde :)

Danke!

**Comment by HellPat** [comment]
"dass man nicht einfach beim ersten Artikel einen Prozentwert eintragen kann "
- genau das war gemeint. Wenn das nicht so gedacht war wie ich das dachte, dann war es ein wenig missverständlich.
  Ich hatte das im Zusammenhang mit dem "Pseudopreis" gesehen und gedacht ich könnte es "Pseudo 20% reduzieren" ohne selbst rechnen zu müssen.

**Comment by dnoegel** [comment]
Hi psren,

i've created a ticket in our internal ticket system in order to address that issue in a later release.
