### ISSUE TITLE
Add config.php to repository

### ISSUE THREAD

**Issue by bcremer** [shopware5/shopware#35]
After cloning the repository it's not possible to execute the installer due to an requirement error.

The file config.php should be included in the repository or documented in the README.md.

Workaround:
touch config.php && chmod ug+w config.php

**Comment by terwey** [comment]
A month ago https://github.com/ShopwareAG/shopware-4/blob/master/config.php.dist got added.
If you run production from a Git clone you don't want your own config.php to be tracked.
`config.php` should be added to `.gitignore` in the repo.

**Comment by bcremer** [comment]
Hi @terwey,

`config.php` ist already present in our `.gitignore`.
