### ISSUE TITLE
Errors in backend after git clone

### ISSUE THREAD

**Issue by terwey** [shopware5/shopware#36]
Hi,

I just did a fresh checkout from Git after forking it. After installation and going to _Configuration -> Settings_ and clicking on _Shop Settings -> Shops_ I get the following:

```
Ups! Ein Fehler ist aufgetreten! Die nachfolgenden Hinweise sollten Ihnen weiterhelfen. 
SQLSTATE[42S22]: Column not found: 1054 Unknown column 's0_.base_url' in 'field list' in Doctrine/DBAL/Connection.php on line 633 Stack trace: 
#0 Doctrine/DBAL/Connection.php(633): PDO->query('SELECT s0_.id A...') 
#1 Doctrine/ORM/Query/Exec/SingleSelectExecutor.php(46): Doctrine\DBAL\Connection->executeQuery('SELECT s0_.id A...', Array, Array, NULL) 
#2 Doctrine/ORM/Query.php(260): Doctrine\ORM\Query\Exec\SingleSelectExecutor->execute(Object(Doctrine\DBAL\Connection), Array, Array) 
#3 Doctrine/ORM/AbstractQuery.php(595): Doctrine\ORM\Query->_doExecute() 
#4 Doctrine/ORM/AbstractQuery.php(432): Doctrine\ORM\AbstractQuery->execute(Array, 2) 
#5 Shopware/Controllers/Backend/Config.php(278): Doctrine\ORM\AbstractQuery->getArrayResult() 
#6 Enlight/Controller/Action.php(135): Shopware_Controllers_Backend_Config->getListAction() 
#7 Enlight/Controller/Dispatcher/Default.php(521): Enlight_Controller_Action->dispatch('getListAction') 
#8 Enlight/Controller/Front.php(214): Enlight_Controller_Dispatcher_Default->dispatch(Object(Enlight_Controller_Request_RequestHttp), Object(Enlight_Controller_Response_ResponseHttp)) 
#9 Shopware/Bootstrap.php(79): Enlight_Controller_Front->dispatch() 
#10 Enlight/Application.php(192): Shopware_Bootstrap->run() 
#11 shopware.php(74): Enlight_Application->run() #12 {main}  
```

(linebreaks are mine...)

Then if I click away the error (cause I got too little to go on now) and add a new Shop (which afaik should have already been added during installation) I get the following error:

```
Ups! Ein Fehler ist aufgetreten! Die nachfolgenden Hinweise sollten Ihnen weiterhelfen. 
SQLSTATE[42S22]: Column not found: 1054 Unknown column 's0_.base_url' in 'field list' in Doctrine/DBAL/Connection.php on line 633 Stack trace: 
#0 Doctrine/DBAL/Connection.php(633): PDO->query('SELECT s0_.id A...') 
#1 Doctrine/ORM/Query/Exec/SingleSelectExecutor.php(46): Doctrine\DBAL\Connection->executeQuery('SELECT s0_.id A...', Array, Array, NULL) 
#2 Doctrine/ORM/Query.php(260): Doctrine\ORM\Query\Exec\SingleSelectExecutor->execute(Object(Doctrine\DBAL\Connection), Array, Array) 
#3 Doctrine/ORM/AbstractQuery.php(595): Doctrine\ORM\Query->_doExecute() 
#4 Doctrine/ORM/AbstractQuery.php(432): Doctrine\ORM\AbstractQuery->execute(Array, 2) 
#5 Shopware/Controllers/Backend/Config.php(278): Doctrine\ORM\AbstractQuery->getArrayResult() 
#6 Enlight/Controller/Action.php(135): Shopware_Controllers_Backend_Config->getListAction() 
#7 Enlight/Controller/Dispatcher/Default.php(521): Enlight_Controller_Action->dispatch('getListAction') 
#8 Enlight/Controller/Front.php(214): Enlight_Controller_Dispatcher_Default->dispatch(Object(Enlight_Controller_Request_RequestHttp), Object(Enlight_Controller_Response_ResponseHttp)) 
#9 Shopware/Bootstrap.php(79): Enlight_Controller_Front->dispatch() 
#10 Enlight/Application.php(192): Shopware_Bootstrap->run() 
#11 shopware.php(74): Enlight_Application->run() #12 {main}  
```

Which is well, the same error ;)

However in the Table _s_core_shops_ there are 2 records, one is referred to as the _Hauptshop Deutsch_ and the other _Englisch_. The _Hauptshop Deutsch_ looks like it was filled out (mostly) correct, however some fields are missing
_Hauptshop Deutsch_
- main_id
- title
- base_path
- secure_host
- secure_base_path
- fallback_id

_Englisch_
- title
- host
- base_path
- hosts
- secure_host
- secure_base_path
- template_id
- document_template_id
- fallback_id

Now there's no mention of the _base_url_ field in this table and not sure yet in which it should be. However I assume something went haywire during the initial install. Hence the issue. Any thoughts?

**Comment by terwey** [comment]
This error is coming back with everything you try to do in the backend. Seems like a serious bug to me. No idea what is causing it.

The Installer didn't have any issues whatsoever with my setup.

**Comment by skloepper** [comment]
Please use the tag/download 4.0.4 or the 4.0.5 release candidate for an installation.
This is the live development version. So it is possible that some database deltas are missing right now.

**Comment by terwey** [comment]
@skloepper Hi, yes I understand that :) I will try the tag and see if that runs (it should I presume). However, the idea was of course to run the latest and greatest... find some bugs, squash them and see how it goes. I did not however expect that the Branch I'm on has broken database deltas :)

Just checked out the tag 4.0.4 and it works. I've found out where it breaks in the new one (it refers to a base_url field that doesn't exist) but I don't know in which direction it's going so not sure if it makes sense to fix :)

**Comment by shredding** [comment]
Have the same issue. Can't get shopware up and running at all, using this:

```
git clone git@github.com:ShopwareAG/shopware-4.git
```

**Comment by dnoegel** [comment]
Hi, you need to run the sql deltas for your shopware database. They can be found in /_sql/deltas. The install script deploys the deltas for the latest release (4.0.4. eg) but not those for the current development version. Hope that helps.

**Comment by shredding** [comment]
Thx, got it up and running right now.
