### ISSUE TITLE
[Feature?] (Sub-)Properties per Category

### ISSUE THREAD

**Issue by terwey** [shopware5/shopware#39]
Hi,

At least in Shopware 3 this is not possible and from my experimentations with Shopware 4 it still doesn't seem to be possible.
I have a set of products that should for the convenience of the user appear in multiple categories. However, every category has a different subset of properties. At the moment I solved it by duplicating the product. This is of course, very cumbersome to update a product on price or availability.

To describe the problem more clearly, I have products that fit into specific models of cars. Now having -every- possible car it fits into set for 1 product makes the list -huge- if you want to filter. The cars itself can be divided into categories which makes the selection of properties already a lot smaller.

What would be perfect for example is having sub-properties. Based on a specific property certain other one's become available. This would solve the problem too. I don't necessarily need categories (this was just a fallback for the current situation).

What are the recommendations here? Or where should I poke around in Shopware to add/extend the functionality needed for this? Am I attacking the problem wrong?

Thank you for your time :)

**Comment by dnoegel** [comment]
Hi @terwey,

currently there is no way to have something like "sub-properties" in SW. You will need to make use of categories and disable the filters for the topmost categories if the filters get too much. I'll move your proposal to our internal ticket system.

**Comment by dnoegel** [comment]
Btw.: You might be interested in grouped filters. This way you can also limit the numbers of filters being shown.

**Comment by terwey** [comment]
Hi @dnoegel,

unfortunately the grouped filters make for duplicates. I solved it by writing an extension: https://github.com/terwey/YTCategoryProperties
(I actually wanted to publish this on the Shopware Extension site but I received a weird dev-prefix so didn't continue)

However sub-filters would still be nicer but still haven't had the time to write such a capability.
