### ISSUE TITLE
Bugs in Shop sites - Groups assignment component

### ISSUE THREAD

**Issue by maff** [shopware5/shopware#40]
There's a bug on the "Content - Shop site" form when assigning/unassigning groups using the arrow buttons instead of double-clicking an entry. Altough there are two different problems I file this as one issue as it is a problem affecting the whole component.

Problem 1:
Assign group (select group from left selectbox, click on the right arrow button): group is assigned on the right side, left list is empty (even if there would be more groups on the left side).

Problem 2:
Unassign a group (select group on right selectbox, click on the left arrow button): group is moved to the left selectbox, but all other entries in the left selectbox are cleared so the moved item is the only one in the left box. The right box is completely empty (even if there are morge assigned groups).

Tested on 4.0.4 and 4.0.5 / FF, Chrome
## 

ORIGINAL ISSUE IN GERMAN:
Im Backend besteht im Menü "Inhalte - Shopseiten" ein Bug (eigentlich zwei) bei der Zuordnung von Seiten zu Gruppen, wenn die Gruppen über die Pfeil-Buttons zugewiesen/entfernt werden. Bei Doppelklick besteht das Problem nicht.

Problem 1:
Gruppe zuweisen (Auswahl Gruppe in der linken Liste, Klick auf Pfeil nach rechts): Gruppe wird rechts zugewiesen, aber Liste links ist anschließend leer.

Problem 2:
Zuweisung entfernen (Auswahl Gruppe in der rechten Leiste, Klick auf Pfeil nach links): Gruppe erscheint in der linken Liste, jedoch ist linke Liste bis auf die gerade entfernte Gruppe leer. Rechte Liste ist komplett leer (auch wenn weitere Gruppen zugewiesen waren).

Getestet auf 4.0.4 und 4.0.5 / FF, Chrome

**Comment by mablae** [comment]
Please write english in Github !

**Comment by mablae** [comment]
Please ONE issue per issue!

**Comment by 3poo** [comment]
i confirm both issues on version 4.05

**Comment by maff** [comment]
@mablae added an english issue report. Couldn't find any guidelines and many existing reports were in german, so I wrote the original version in german. I'll leave this as single issue though as I think it is a single bug in the component with the two described consequences.

**Comment by dnoegel** [comment]
Hi,

we've recently addressed that issue. The group model of the site module needs an 'id' field: https://github.com/ShopwareAG/shopware-4/blob/master/templates/_default/backend/site/model/groups.js

**Comment by mablae** [comment]
You mean this commit:  46cd05cae95ea312a0f573fd19533baa0765eb5b ? 

Then this issue could be closed, I would say :+1: 

Thanks @maff
