### ISSUE TITLE
Use feature branches

### ISSUE THREAD

**Issue by mablae** [shopware5/shopware#41]
Please add feature branches for development versions.

**Comment by terwey** [comment]
Git Flow is an awesome Git extension to help keep track of feature (and other) branches.
Explanation:
http://nvie.com/posts/a-successful-git-branching-model/

Extension:
https://github.com/nvie/gitflow

**Comment by bcremer** [comment]
We already use a feature-branch-based workflow for our internal development. May be we will expose some of our internal development branches to github in the future.
