### ISSUE TITLE
setPricegroup in Shopware\Models\Article\Price\Price does nothing

### ISSUE THREAD

**Issue by shredding** [shopware5/shopware#44]
`setPricegroup()` references a property named `priceGroup` that does not exist. The associated column 'pricegroup' can only be set like:

```
 $groupRepository = Shopware()->Models()->getRepository('Shopware\Models\Customer\Group');
    /** @var Shopware\Models\Customer\Group $group  */
    $group = array_shift($groupRepository->findBy(array('key' => 'EK')));
$myPrice->setCustomerGroup($group);
```

**Comment by dnoegel** [comment]
Hi shredding,

You are right: There is no attribute 'priceGroup' in the Price model - the setter function unnecessary: There is the setter 'setCustomerGroup' which sets the 'customerGroup" attribute which references the column 'pricegroup' in s_articles_prices.

We'll cleanup this in one of the following releases. For the time being, you should be able to work properly with the setCustomerGroup setter.
