### ISSUE TITLE
Not accepted AGBs on checkout triggers confirm action even twice

### ISSUE THREAD

**Issue by shredding** [shopware5/shopware#45]
If you register `Enlight_Controller_Action_PostDispatch_Frontend_Checkout` the event for `confirm` Action is triggered twice (but the action itself is correctly called only once). 

This causes a serious issue in my extension :)

Steps to rebuild this issue:
1. Download http://digitale-avantgarde.com/Example.zip
2. Clear shopware cache & install the Example Extension
3. Finish the checkout process but DO NOT accept the AGB
4. Look your Chrome console printing out "Confirm was called" twice.

**Comment by shredding** [comment]
Anyone?

**Comment by dnoegel** [comment]
Hi shredding,

have you tried to check for the AGB field in your extension? This way you might be able to sort out the additional action. Right know I think this is caused by some controller forwarding - but I need to have a closer look at that by time.

**Comment by shredding** [comment]
> have you tried to check for the AGB field in your extension

No, that's not the reason. I'm not taking care of the T&C field at all. I tracked that down a little, the forwarding looks okay to me, finishActions forwards to confirm ...

**Comment by dnoegel** [comment]
Yes, I agree with that. I just wanted to recommend to make use of the view variables and check if sAGBError was set to true, for example.

This does not solve the fact that confirmAction is raised twice - but you are able to distinct between regular confirmActions and those with an sAGBError. I thought this might help you, to solve the issues, you have with your extension.

**Comment by shredding** [comment]
Ah, I've already worked around that issue in my extension, but want to get rid of the boilerplate.

**Comment by shredding** [comment]
Just to note: This issue does as well occur when forwarding back from paymentAction. I assume this happens on every forward to confirmAction.

**Comment by dnoegel** [comment]
Hi shredding,

I'll move this issue to our internal bug tracker. You can access your ticket here: http://jira.shopware.de/Widgets/Jira/?ticket=SW-5158

If you have additional questions, please make user of the possibility to comment there.

Thanks and best regards,

Daniel
