### ISSUE TITLE
Cannot import database on chrome, not found in cookies error

### ISSUE THREAD

**Issue by beberlei** [shopware5/shopware#46]
When in do the install tool on chrome, it fails on the database import step with an error that the database connection details could not been found, asking if cookies are enabled.

**Comment by bcremer** [comment]
Hi Benjamin, could you please provide further information about your environment setup (Browser, Web-Server, Client-OS, etc).

Also, what version of shopware are you running? The latest git-version or a release package form http://wiki.shopware.de/Downloads_cat_448.html.

**Comment by beberlei** [comment]
I downloaded the release package and using Chromium 22.0.1229.94 Ubuntu 12.10

**Comment by mablae** [comment]
@beberlei Did you rename config.php.dist ?

**Comment by beberlei** [comment]
No, this was the first time using the install tool.

**Comment by dnoegel** [comment]
Hi @beberlei,

we still cannot reproduce this issue, so I'll close it for now. Please feel free to reopen it, if the problem persists for you.
