### ISSUE TITLE
Better support for I18n in backend config

### ISSUE THREAD

**Issue by wdJer** [shopware5/shopware#48]
Shopware_Controllers_Backend_Config::getFormAction() currently only translates the label.
If you have a description including the corresponding translation added to your Form-Field it's not shown on the module configuration page.
It's also not possible to translate values of e.G. select fields.

**Comment by dnoegel** [comment]
Hi,

thanks for opening this issue. In order to have all issues at one place, we've decided to move the GitHub issues to our own bug tracker which can be found at http://jira.shopware.de.

Your ticket can be found at the following url:

http://jira.shopware.de/?ticket=sw-6988
