### ISSUE TITLE
Feature Request: Wrap cart items in smarty blocks

### ISSUE THREAD

**Issue by shredding** [shopware5/shopware#50]
Please add a smarty block to _default/checkout/cart.tpl around the lines 82-86, to make it possible to adjust the basket item listing.

```
{* Article items *}
{block name='frontend_checkout_cart_article_items'}
{foreach name=basket from=$sBasket.content item=sBasketItem key=key}
    {include file='frontend/checkout/cart_item.tpl'}    
{/foreach}
{/block}
```

**Comment by dnoegel** [comment]
Hi shredding,

I'll move this issue to our internal bug tracker. You can access your ticket here: http://jira.shopware.in/jira/browse/SW-5159

If you have additional questions, please make use of the comment function on that tracker.

Thanks and best regards,

Daniel

**Comment by lennartdiedrich** [comment]
Daniel, your link seems to point to an internal location (inranet) of the jira, which is not accessible over the internet. I think the correct one is: http://jira.shopware.de/Widgets/Jira/?ticket=SW-5159

**Comment by dnoegel** [comment]
Thanks a lot, I mixed it up :-)
