### ISSUE TITLE
Installation dir

### ISSUE THREAD

**Issue by terwey** [shopware5/shopware#51]
Hi,

the installation dir is currently in the master / community-branch which means that on a fork you cannot remove the install dir without Git going insane about it. Sure I can ignore it and never commit it but it would be nicer if there's a different way.
I'm thinking either a git submodule for initial setup which you can remove (or not fork at all).

Thoughts?

**Comment by bcremer** [comment]
Hi,

thank's for your feedback.

Why would you need to remove the installation dir? The installation via git is not recommended for production usage.
For production usage you can find the release package at http://wiki.shopware.de/Downloads_cat_448.html.

As an alternative you could add the installation dir to the .gitignore file.

A git submodule sounds interesting but adds some complexity to the installation process.

We will revisit your idea when we implement composer for our dependency managment.

**Comment by terwey** [comment]
Hi @bcremer,

Adding it to the .gitignore means my own fork would not have the installation dir included which makes that difficult to maintain again compared to the normal upstream.

As to why run directly from the git? Well you do tag your versions so I can just grab the current one. And I prefer to work in a version controlled environment vs some tarballs that might mess up the whole place and don't have a backup in place ;)

Composer can also sound the problem because the Installation dir can just be moved into a different Repo and can be pulled in the moment you install via Composer.

The other possibility is renaming the install directory in git to something like install.dist and just include .dist in the .gitignore. Then locally you rename it to install and all is well. Just have the scripts check if it's current dir includes the word 'dist' and if so, die() :)

**Comment by bcremer** [comment]
Hi @terwey,

you can just setup a global .gitignore file:

``` bash
git config --global core.excludesfile ~/.gitignore_global
echo "/var/www/shopware/install/" > ~/.gitignore_global
```

So you don't have to mess up your local shopware-git clone.

**Comment by terwey** [comment]
Hi @bcremer,

I totally did not think of that. Good idea until the 'problem' is resolved in a nicer way :) I'll leave the issue open until another solution has been found. But it's up to you I guess.

Off topic: I'm having trouble upgrading from 3.5.6 to 4.0.5 should I post that as an issue here on Github or somewhere else? Not sure how those issues are tracked. I already posted the problem here: http://forum.shopware.de/installation-einstieg-f54/database-upgrade-problems-t11356.html
