### ISSUE TITLE
Image Article import fails

### ISSUE THREAD

**Issue by terwey** [shopware5/shopware#55]
So after having redone the import a few times to find out it's running in against the max execution time I've now raised that to 1 whole hour for the test enviroment only. However... not other stuff fails :) This is the HAR result from the Chrome Dev tools:
`{
  "log": {
    "version": "1.2",
    "creator": {
      "name": "WebInspector",
      "version": "537.17"
    },
    "pages": [],
    "entries": [
      {
        "startedDateTime": "2013-01-31T11:03:21.342Z",
        "time": 0,
        "request": {
          "method": "GET",
          "url": "data:image/gif;base64,R0lGODlhAQABAID/AMDAwAAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==",
          "httpVersion": "HTTP/1.1",
          "headers": [],
          "queryString": [],
          "cookies": [],
          "headersSize": 97,
          "bodySize": 0
        },
        "response": {
          "status": 0,
          "statusText": "",
          "httpVersion": "HTTP/1.1",
          "headers": [],
          "cookies": [],
          "content": {
            "size": 43,
            "mimeType": "image/gif"
          },
          "redirectURL": "",
          "headersSize": 13,
          "bodySize": 0
        },
        "cache": {},
        "timings": {
          "blocked": 0,
          "dns": -1,
          "connect": -1,
          "send": -1,
          "wait": -1,
          "receive": 0,
          "ssl": -1
        }
      },
      {
        "startedDateTime": "2013-01-31T11:03:21.502Z",
        "time": 0,
        "request": {
          "method": "GET",
          "url": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAASCAIAAAAVNSPrAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAJ0lEQVQIHQXBgQ0AAAjDoKX/3yxCaFss07ZYyNZZ6Ih1dDTrrKM7D9KDJfc8DkCSAAAAAElFTkSuQmCC",
          "httpVersion": "HTTP/1.1",
          "headers": [
            {
              "name": "Referer",
              "value": "http://4.shop.caramo.de/backend/"
            },
            {
              "name": "User-Agent",
              "value": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_2) AppleWebKit/537.17 (KHTML, like Gecko) Chrome/24.0.1312.52 Safari/537.17"
            }
          ],
          "queryString": [],
          "cookies": [],
          "headersSize": 369,
          "bodySize": 0
        },
        "response": {
          "status": 0,
          "statusText": "",
          "httpVersion": "HTTP/1.1",
          "headers": [],
          "cookies": [],
          "content": {
            "size": 117,
            "mimeType": "image/png",
            "compression": 130
          },
          "redirectURL": "",
          "headersSize": 13,
          "bodySize": -13
        },
        "cache": {},
        "timings": {
          "blocked": 0,
          "dns": -1,
          "connect": -1,
          "send": 0,
          "wait": 0,
          "receive": 0,
          "ssl": -1
        }
      },
      {
        "startedDateTime": "2013-01-31T11:03:21.503Z",
        "time": 0,
        "request": {
          "method": "GET",
          "url": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAASCAIAAAAVNSPrAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAK0lEQVQIW2NIePSf6d0fBqZb7xmY/v1lYPoPwv/QaCBm+IcmDsQMUHGgPgDs0yDjUYa+3gAAAABJRU5ErkJggg==",
          "httpVersion": "HTTP/1.1",
          "headers": [
            {
              "name": "Referer",
              "value": "http://4.shop.caramo.de/backend/"
            },
            {
              "name": "User-Agent",
              "value": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_2) AppleWebKit/537.17 (KHTML, like Gecko) Chrome/24.0.1312.52 Safari/537.17"
            }
          ],
          "queryString": [],
          "cookies": [],
          "headersSize": 377,
          "bodySize": 0
        },
        "response": {
          "status": 0,
          "statusText": "",
          "httpVersion": "HTTP/1.1",
          "headers": [],
          "cookies": [],
          "content": {
            "size": 121,
            "mimeType": "image/png",
            "compression": 134
          },
          "redirectURL": "",
          "headersSize": 13,
          "bodySize": -13
        },
        "cache": {},
        "timings": {
          "blocked": 0,
          "dns": -1,
          "connect": -1,
          "send": 0,
          "wait": 0,
          "receive": 0,
          "ssl": -1
        }
      },
      {
        "startedDateTime": "2013-01-31T11:03:21.634Z",
        "time": 9,
        "request": {
          "method": "GET",
          "url": "about:blank",
          "httpVersion": "HTTP/1.1",
          "headers": [
            {
              "name": "Referer",
              "value": "http://4.shop.caramo.de/backend/"
            },
            {
              "name": "User-Agent",
              "value": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_2) AppleWebKit/537.17 (KHTML, like Gecko) Chrome/24.0.1312.52 Safari/537.17"
            }
          ],
          "queryString": [],
          "cookies": [],
          "headersSize": 202,
          "bodySize": 0
        },
        "response": {
          "status": 0,
          "statusText": "",
          "httpVersion": "HTTP/1.1",
          "headers": [],
          "cookies": [],
          "content": {
            "size": 0,
            "mimeType": "text/html",
            "compression": 0
          },
          "redirectURL": "",
          "headersSize": 13,
          "bodySize": 0
        },
        "cache": {},
        "timings": {
          "blocked": 0,
          "dns": -1,
          "connect": -1,
          "send": -1,
          "wait": -1,
          "receive": 9,
          "ssl": -1
        }
      },
      {
        "startedDateTime": "2013-01-31T11:03:21.710Z",
        "time": 195623,
        "request": {
          "method": "POST",
          "url": "http://4.shop.caramo.de/backend/ImportExport/import",
          "httpVersion": "HTTP/1.1",
          "headers": [
            {
              "name": "Accept",
              "value": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
            },
            {
              "name": "Referer",
              "value": "http://4.shop.caramo.de/backend/"
            },
            {
              "name": "Origin",
              "value": "http://4.shop.caramo.de"
            },
            {
              "name": "User-Agent",
              "value": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_2) AppleWebKit/537.17 (KHTML, like Gecko) Chrome/24.0.1312.52 Safari/537.17"
            },
            {
              "name": "Content-Type",
              "value": "multipart/form-data; boundary=----WebKitFormBoundarylGLDm0fXUBqTPwTd"
            }
          ],
          "queryString": [],
          "cookies": [],
          "headersSize": 433,
          "bodySize": 279,
          "postData": {
            "mimeType": "multipart/form-data; boundary=----WebKitFormBoundarylGLDm0fXUBqTPwTd",
            "text": "------WebKitFormBoundarylGLDm0fXUBqTPwTd\r\nContent-Disposition: form-data; name=\"type\"\r\n\r\nimages\r\n------WebKitFormBoundarylGLDm0fXUBqTPwTd\r\nContent-Disposition: form-data; name=\"file\"; filename=\"images.csv\"\r\nContent-Type: text/csv\r\n\r\n\r\n------WebKitFormBoundarylGLDm0fXUBqTPwTd--\r\n"
          }
        },
        "response": {
          "status": 0,
          "statusText": "",
          "httpVersion": "HTTP/1.1",
          "headers": [],
          "cookies": [],
          "content": {
            "size": 0,
            "compression": 0
          },
          "redirectURL": "",
          "headersSize": 13,
          "bodySize": 0
        },
        "cache": {},
        "timings": {
          "blocked": 0,
          "dns": -1,
          "connect": -1,
          "send": -1,
          "wait": -1,
          "receive": null,
          "ssl": -1
        }
      },
      {
        "startedDateTime": "2013-01-31T11:06:07.329Z",
        "time": 30002,
        "request": {
          "method": "GET",
          "url": "http://4.shop.caramo.de/backend/login/getLoginStatus?_dc=1359630367329",
          "httpVersion": "HTTP/1.1",
          "headers": [
            {
              "name": "Referer",
              "value": "http://4.shop.caramo.de/backend/"
            },
            {
              "name": "User-Agent",
              "value": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_2) AppleWebKit/537.17 (KHTML, like Gecko) Chrome/24.0.1312.52 Safari/537.17"
            },
            {
              "name": "X-Requested-With",
              "value": "XMLHttpRequest"
            }
          ],
          "queryString": [
            {
              "name": "_dc",
              "value": "1359630367329"
            }
          ],
          "cookies": [],
          "headersSize": 295,
          "bodySize": 0
        },
        "response": {
          "status": 0,
          "statusText": "",
          "httpVersion": "HTTP/1.1",
          "headers": [],
          "cookies": [],
          "content": {
            "size": 0,
            "compression": 0
          },
          "redirectURL": "",
          "headersSize": 13,
          "bodySize": 0
        },
        "cache": {},
        "timings": {
          "blocked": 0,
          "dns": -1,
          "connect": -1,
          "send": -1,
          "wait": -1,
          "receive": null,
          "ssl": -1
        }
      },
      {
        "startedDateTime": "2013-01-31T11:06:37.333Z",
        "time": 4,
        "request": {
          "method": "GET",
          "url": "http://4.shop.caramo.de/backend",
          "httpVersion": "HTTP/1.1",
          "headers": [],
          "queryString": [],
          "cookies": [],
          "headersSize": 46,
          "bodySize": 0
        },
        "response": {
          "status": 301,
          "statusText": "Moved Permanently",
          "httpVersion": "HTTP/1.1",
          "headers": [],
          "cookies": [],
          "content": {
            "size": 0,
            "mimeType": "text/html"
          },
          "redirectURL": "",
          "headersSize": 32,
          "bodySize": 0
        },
        "cache": {},
        "timings": {
          "blocked": 0,
          "dns": -1,
          "connect": -1,
          "send": -1,
          "wait": -1,
          "receive": 0,
          "ssl": -1
        }
      },
      {
        "startedDateTime": "2013-01-31T11:06:37.337Z",
        "time": 299997,
        "request": {
          "method": "GET",
          "url": "http://4.shop.caramo.de/backend/",
          "httpVersion": "HTTP/1.1",
          "headers": [
            {
              "name": "Referer",
              "value": "http://4.shop.caramo.de/backend/"
            },
            {
              "name": "User-Agent",
              "value": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_2) AppleWebKit/537.17 (KHTML, like Gecko) Chrome/24.0.1312.52 Safari/537.17"
            }
          ],
          "queryString": [],
          "cookies": [],
          "headersSize": 223,
          "bodySize": 0
        },
        "response": {
          "status": 0,
          "statusText": "",
          "httpVersion": "HTTP/1.1",
          "headers": [],
          "cookies": [],
          "content": {
            "size": 0,
            "compression": 0
          },
          "redirectURL": "",
          "headersSize": 13,
          "bodySize": 0
        },
        "cache": {},
        "timings": {
          "blocked": 0,
          "dns": -1,
          "connect": -1,
          "send": -1,
          "wait": -1,
          "receive": null,
          "ssl": -1
        }
      },
      {
        "startedDateTime": "2013-01-31T11:11:37.334Z",
        "time": 3,
        "request": {
          "method": "GET",
          "url": "http://4.shop.caramo.de/backend",
          "httpVersion": "HTTP/1.1",
          "headers": [],
          "queryString": [],
          "cookies": [],
          "headersSize": 46,
          "bodySize": 0
        },
        "response": {
          "status": 301,
          "statusText": "Moved Permanently",
          "httpVersion": "HTTP/1.1",
          "headers": [],
          "cookies": [],
          "content": {
            "size": 0,
            "mimeType": "text/html"
          },
          "redirectURL": "",
          "headersSize": 32,
          "bodySize": 0
        },
        "cache": {},
        "timings": {
          "blocked": 0,
          "dns": -1,
          "connect": -1,
          "send": -1,
          "wait": -1,
          "receive": 0,
          "ssl": -1
        }
      },
      {
        "startedDateTime": "2013-01-31T11:11:37.337Z",
        "time": -1,
        "request": {
          "method": "GET",
          "url": "http://4.shop.caramo.de/backend/",
          "httpVersion": "HTTP/1.1",
          "headers": [
            {
              "name": "Referer",
              "value": "http://4.shop.caramo.de/backend/"
            },
            {
              "name": "User-Agent",
              "value": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_2) AppleWebKit/537.17 (KHTML, like Gecko) Chrome/24.0.1312.52 Safari/537.17"
            }
          ],
          "queryString": [],
          "cookies": [],
          "headersSize": 223,
          "bodySize": 0
        },
        "response": {
          "status": 0,
          "statusText": "",
          "httpVersion": "HTTP/1.1",
          "headers": [],
          "cookies": [],
          "content": {
            "size": 0,
            "compression": 0
          },
          "redirectURL": "",
          "headersSize": 13,
          "bodySize": 0
        },
        "cache": {},
        "timings": {
          "blocked": 0,
          "dns": -1,
          "connect": -1,
          "send": -1,
          "wait": -1,
          "receive": -1,
          "ssl": -1
        }
      }
    ]
  }
}`

Feeded CSV: Images are hosted on the original domain (the testing is a sub-domain, same server) and are readable. It imports a few images and then runs out of time.

_edit_: oddly enough it does continue to execute the import. The browser however is having issues figuring out if it is or not.
I don't know atm (didn't check yet) how the import tool does this. Does it feed 1 line of CSV per time to the script and wait for a respond or does it just throw a file and hope it works? Cause the progressbar just keeps running happily but isn't realistic at all :(

**Comment by dnoegel** [comment]
Hi terwey,

currentyl the script copies the CSV to your server and runs the import. This iterates all lines, create the corresponding Objects and persists them. The progressbar is running in pulse-mode until the requests returns. In so far it only indicates that "something is happening". In some situation it might keep pulsing even if something in the backend went horribly wrong. 

As stated in the other issue: This behaviour might be a bottle neck when importing large amounts of data. In so far I suggest to split your CSV. How many lines are you trying to import?

**Comment by terwey** [comment]
Hi @dnoegel,

oddly enough the script did seem to be running after the browser session itself had died. It never finished uploading all the images but it did manage to do most.
However the script does do what I suspected, it does not cut up the CSV. I'll take a look when I have time to see if I can maybe 'fix' that.

I imagine a staggered script, take the CSV, read the first 10 lines, parse and return the last line number to the browser. The JS could then say: ok now process 11 to 21. And the process repeats until the script is done. This would prevent a max-execution time problem -and- would create a working progress bar for the backend.

But there are many ways to Rome and I just woke up so... ;)

**Comment by dnoegel** [comment]
Hi terwey,

jap, that would be a possible solution; we've already implemented similar behaviour in our article configurator or our migration script. :)

**Comment by dnoegel** [comment]
Hi terwey, 

as we've already an internal ticket for this issue, I'll close this one. For additional comments and questions please use our Jira-Bug-Tracker: http://jira.shopware.de/Widgets/Jira/?ticket=SW-4580
