### ISSUE TITLE
akward entry in 's_cms_support_fields' within 'shopware-4/install/assets/sql/sw4_clean.sql'

### ISSUE THREAD

**Issue by AR0x7E7** [shopware5/shopware#59]
hey guys, knowing it's not a big issue still I would like to know what the akward entry:

(12, '', 'sdfg', '', '', 0, 0, 'sdf', '', '', '0000-00-00 00:00:00', 0, '')

in table 's_cms_support_fields' (I assume) created with '.../sw4_clean.sql' is used for?

Thx!

**Comment by bcremer** [comment]
Hey @AR0x7E7,

good catch :+1: 

I created a ticket in our internal repo. This entry will be deleted in the next minor versionl.

Thank's for your contribution.
