### ISSUE TITLE
Product properties: broken option and value order update with drag&drop

### ISSUE THREAD

**Issue by AR0x7E7** [shopware5/shopware#60]
Hey guys, some kind of nasty bug: as stated in the Product properties menu after reordering option or value items the new order will not be saved - this also affects directly the filter appearance at the frontend. 

Added a pic to illustrate what I mean.

![issue1](https://f.cloud.github.com/assets/1496858/196420/c52cd1d6-801a-11e2-8e20-a9ab9701a19f.jpg)

Sure one could work around and delete all items & reinsert them in the correct order, but I guess in the long run this is not the ideal solution.

**Comment by dnoegel** [comment]
Hi @AR0x7E7,

thanks for reporting this issue. I've created a ticket in our bug tracker: http://jira.shopware.de/Widgets/Jira/?ticket=SW-5338
