### ISSUE TITLE
Language / Localisation setting derived from HTTP-Header instead of preference

### ISSUE THREAD

**Issue by AR0x7E7** [shopware5/shopware#61]
Hey guys,
running a shop with German localisation set under 'Basic Settings/Shop Settings/Shop/' AND choosing 'Deutsch (Deutsch)' as language at backend login page it happens to me that some Snippet components (like 'Order status' or 'Payment status') appear still in English (see below).

![Bildschirmfoto 2013-02-27 um 09 01 24](https://f.cloud.github.com/assets/1496858/200088/48b5e986-80b9-11e2-9754-48dfc8082f5e.png)

However, I figuered out that this behavior is due to the HTTP Post Header Line:
Accept-Language:en-US,en;q=0.8

On the other side, when my browser sends the following Line (different System):
Accept-Language:de-DE,de;q=0.8,en-US;q=0.6,en;q=0.4

the Snippets appear in German though I choose 'English (United Kingdom)' at login (see below).

![Bildschirmfoto 2013-02-27 um 09 43 36](https://f.cloud.github.com/assets/1496858/200130/da58b9b8-80b9-11e2-8105-5d6b72cfb083.png)

Finally I would say that the language selection for (at least the above mentioned) Snippets is "broken", as user selection should overwrite browser default.

**Comment by OliverSkroblin** [comment]
Hi,

we will verify the issue as soon as possible. You can trace the process in our public issue tracker:
http://jira.shopware.de/?ticket=SW-6745

**Comment by dnoegel** [comment]
Hi,

thanks for opening this issue. In order to have all issues at one place, we've decided to move the GitHub issues to our own bug tracker which can be found at http://jira.shopware.de.

Your ticket can be found at the following url:

http://jira.shopware.de/?ticket=SW-6745
