### ISSUE TITLE
'Close shop due to maintenance' requires cache flush in order to work.

### ISSUE THREAD

**Issue by AR0x7E7** [shopware5/shopware#62]
Hey guys,
I just noticed that after I close the web shop with the checkbox under 'Basic Settings/System/Service' (while assigning an exception IP, not sure if this affects this issue in any way) the frontend continues to be available for customers.

I need to manually empty the cache in order to make the maintenance message appear.
In my opinion this is not the correct way for this to work.
It should be possible to integrate the cache flush step after the 'Save' confirmation (maybe some warning box could appear, that the cache will be flushed or something).

**Comment by dnoegel** [comment]
Hi @AR0x7E7,

thanks for your report; currently all config Variables are bing cached by default. I've create an internal ticket for this issue and referenced this ticket there.
