### ISSUE TITLE
Previewing invoice PDF, getting: 'The identifier id is missing for a query of Shopware\Models\Shop\Currency'

### ISSUE THREAD

**Issue by AR0x7E7** [shopware5/shopware#66]
Hey guys,
I just noticed that somehow the pdf invoice (same for other 3 document types) preview function (accessed trough: configuration/basic configuration/) is broken, as the following error is thrown:

Ups! Ein Fehler ist aufgetreten!
Die nachfolgenden Hinweise sollten Ihnen weiterhelfen.

The identifier id is missing for a query of Shopware\Models\Shop\Currency in Doctrine/ORM/ORMException.php on line 150
Stack trace:
#0 Doctrine/ORM/EntityRepository.php(116): Doctrine\ORM\ORMException::missingIdentifierField('Shopware\Models...', 'id')
#1 Shopware/Components/Model/ModelRepository.php(164): Doctrine\ORM\EntityRepository->find(NULL, 0, NULL)
#2 Shopware/Components/Document.php(461): Shopware\Components\Model\ModelRepository->find(NULL)
#3 Shopware/Components/Document.php(162): Shopware_Components_Document->setOrder(Object(Shopware_Proxies_ShopwareModelsDocumentOrderProxy))
#4 Shopware/Controllers/Backend/Document.php(115): Shopware_Components_Document::initDocument(NULL, '4', Array)
#5 Enlight/Controller/Action.php(135): Shopware_Controllers_Backend_Document->indexAction()
#6 Enlight/Controller/Dispatcher/Default.php(521): Enlight_Controller_Action->dispatch('indexAction')
#7 Enlight/Controller/Front.php(214): Enlight_Controller_Dispatcher_Default->dispatch(Object(Enlight_Controller_Request_RequestHttp), Object(Enlight_Controller_Response_ResponseHttp))
#8 Shopware/Bootstrap.php(79): Enlight_Controller_Front->dispatch()
#9 Enlight/Application.php(192): Shopware_Bootstrap->run()
#10 shopware.php(74): Enlight_Application->run()
#11 {main}

However, if I want to generate a invoice out of the order tab, it is working flawlessly.

**Comment by dnoegel** [comment]
Hi @AR0x7E7 

thanks for your report. I was able to reproduce this behavior and created a ticket in our internal ticket system.

Thanks for your effort
