### ISSUE TITLE
Tag for 4.0.7 Release

### ISSUE THREAD

**Issue by lennartdiedrich** [shopware5/shopware#70]
Why is there a tag vor nearly each shopware version (even 4.0.6 RC versions) but not for version 4.0.7?

**Comment by bcremer** [comment]
Hi Lennart,

the Release was tagged in our internal Repo but not pushed to github. I just fixed that ;)

Thanks for your contribution :+1:

**Comment by lennartdiedrich** [comment]
Thank you. Sorry, if I sounded a bit harsh but I asked several times on IRC channel while "officials" were online and no one seemed to care.
