### ISSUE TITLE
empty form causes 'fatal error' at new customer registration 

### ISSUE THREAD

**Issue by AR0x7E7** [shopware5/shopware#71]
Hi guys,

so sending an empty new customer registration form (../register and ./register/saveRegister) makes PHP crash with following error:

Fatal error: Cannot use string offset as an array in
/usr/www/users/swissmk/swissmobilia-parts.de/engine/Library/Smarty/sysplugins/smarty_internal_templatecompilerbase.php on line 306

But unfortunately this only happens on my live system - also a fresh new install of Shopware delivers the same failure.

On my local testing system both the mirrored live version and a fresh installed version work flawlessly.

My guess is, that it has something to do with the PHP Version as for my local testing system I run PHP 5.3.10 but my hoster uses 5.3.24.

However, I would appreciate any help to solve this issue.

I also posted a new thread in the shopware community forum, you can find it here: http://forum.shopware.de/allgemein-f25/leeres-registrierung-formular-fuhrt-zu-fatal-error-t12954.html

Greetings
AR

**Comment by OliverSkroblin** [comment]
Hi,
thanks for your contribution.
We solve the problem with the following commit:
https://github.com/ShopwareAG/shopware-4/commit/35b373e92e678815ee34c1d799a8a51608ec4afb

The problem is the Zend_Session initialisation with an ArrayObject class.
