### ISSUE TITLE
Subshop / Sprachen - Übersetzungs-Bug

### ISSUE THREAD

**Issue by ottscho** [shopware5/shopware#73]
http://jira.shopware.de/Widgets/Jira/?ticket=SW-5881

Übersetzungen werden anhand der shopID gespeichert und nicht anhand der localeID.
Das kommt zu Fehlern beim Import von Artikeln per API und wenn die locale Englisch bei mehreren Subshops verwendet wird.

**Comment by dnoegel** [comment]
Hi,

danke für den Report. Da es ja schon das entsprechende Jira-Ticket gibt, mache ich an dieser Stelle erstmal zu.
