### ISSUE TITLE
Doppeltes $app = Slim::getInstance();

### ISSUE THREAD

**Issue by cKehres** [shopware5/shopware#8]
https://github.com/ShopwareAG/shopware-4/blob/master/check/index.php#L124
Zeile 121 ff

// Step 1: Select language
$app->map('/', function () {
    $app = Slim::getInstance();
    $app = Slim::getInstance();
    // Check system requirements

Muss hier die Slim::getInstance(); 2 mal aufgerufen werden? Sieht mir etwas komisch aus...

**Comment by sthamann** [comment]
Das ist tatsächlich überflüssig - haben wir korrigiert. Danke
