### ISSUE TITLE
Customer fields not overwritable

### ISSUE THREAD

**Issue by shredding** [shopware5/shopware#80]
Due to the documentation, I should be able to change the labels of textfields in customer billings like that - but it has no effect.

This issue seems common, as I found multiple threads where people did not get it to work.

This is how i added the label:

```
+------+------------------------------+--------+----------+----------------------+----------+---------------------+---------------------+
| id   | namespace                    | shopID | localeID | name                 | value    | created             | updated             |
+------+------------------------------+--------+----------+----------------------+----------+---------------------+---------------------+
| 3130 | backend/customer/view/detail |      1 |        1 | billing/text_1_label | Testtest | 2013-06-13 00:00:00 | 2013-06-19 00:00:00 |
+------+------------------------------+--------+----------+----------------------+----------+---------------------+---------------------+
1 row in set (0,16 sec)
```

**Comment by OliverSkroblin** [comment]
Hi,

the backend snippets are translated via the snippet files in /snippets/backend.
At the moment we have no, update save solution to customize the backend snippets.
For the moment you can override the snippet translation in the customer main.ini file in the snippet/backend folder.

**Comment by dnoegel** [comment]
Hi  @shredding,

thanks for opening this issue, as Oliver stated, there is currently no solution for that - but a ticket in our internal system, so I'll close this issue here for now.
