### ISSUE TITLE
Enlight_Loader::checkFile allow round brackets for windows 64bit compatibility

### ISSUE THREAD

**Issue by DaHaiz** [shopware5/shopware#81]
Hey guys,

as i've just installed shopware on my local windows 64 box, i have a directory "Program FIles (x86)" for 32bit programs. but this path doesnt pass the regex defined in `Enlight_Loader::checkFile()`.
I think we should change the regex to `/[^a-z0-9()\\/\\\\_. :-]/i` to allow square brackets. otherwise it wont work if webserver document root lies inside this directory as it is per default.

**Comment by dnoegel** [comment]
Hi,

thanks for opening this issue. In order to have all issues at one place, we've decided to move the GitHub issues to our own bug tracker which can be found at http://jira.shopware.de.

Your ticket can be found at the following url:

http://jira.shopware.de/?ticket=sw-6987
