### ISSUE TITLE
missing attribute 'text/javascript' and CDATA decorator for javascript in templates/_default/widgets/index/statistic_include.tpl

### ISSUE THREAD

**Issue by AR0x7E7** [shopware5/shopware#83]
Hey there,
once again the attribute 'text/javascript' is missing plus the decoration with CDATA tags (without validator service goes nuts ;) )

Greetings.

**Comment by OliverSkroblin** [comment]
Hi,

we added the issue to our internal ticket system:
http://jira.shopware.de/?ticket=SW-6742
