### ISSUE TITLE
undocumented security flaw

### ISSUE THREAD

**Issue by nonchip** [shopware5/shopware#86]
the change from PHP clearing the cache to a shell script clearing it is undocumented, and also very insecure, as PHP has to be configured to (re)allow exec, a function disabled on most hosts.

**Comment by bcremer** [comment]
Could you please elaborate where the cache cleaning is done with a shell script?
The cache cleaning in the core is mostly done in `engine/Shopware/Controllers/Backend/Cache.php`.  

I think you are referring to `cache/clear_cache.sh`. This script is not called from within Shopware.
It's meant to be used by developers on the command line.
