### ISSUE TITLE
No error popup on enable()

### ISSUE THREAD

**Issue by enesf** [shopware5/shopware#91]
I'm not quite sure if this is really a issue or "works as designed". Anyhow, we have developed a module where we throw an exception on enable() if some conditions are not met, so the plugin won't be activated and a message would be shown what conditions weren't met.

The issue is that the exception message is not shown on the client side. We suspect that the message shown on saveForm() blocks the message of the exception.

To reproduce just throw an Exception (with message) in Bootstrap > enable().

**Comment by enesf** [comment]
Forgot to mention that we tested on version 4.1.0 of Shopware.

**Comment by dnoegel** [comment]
Hi,

thanks for opening this issue. In order to have all issues at one place, we've decided to move the GitHub issues to our own bug tracker which can be found at http://jira.shopware.de.

Your ticket can be found at the following url:

http://jira.shopware.de/?ticket=sw-6986
