### ISSUE TITLE
several issues with API image creation/assignment

### ISSUE THREAD

**Issue by nyov** [shopware5/shopware#93]
I believe I found a few issues with the image related API functions in [Article.php](https://github.com/ShopwareAG/shopware-4/blob/master/engine/Shopware/Components/Api/Resource/Article.php#L1270) while testing Shopware.
1. `$this->getManager()->getRepository('Shopware\Models\Article\Image')->find($imageData['id']);`[(L1289)](https://github.com/ShopwareAG/shopware-4/blob/master/engine/Shopware/Components/Api/Resource/Article.php#L1289) does not seem to work correctly. It errors out if the id does not exist, but doesn't assign an image if it does. Using `mediaId` instead works correctly (L1331).
2. Using a 'link' attribute while creating an Article will upload the image into Shopware even if creating the article later fails for other reasons (duplicate sku or something), this could lead to duplicate or unassigned images floating around in shopware.
3.  most important: [`unset($data['images']);`](https://github.com/ShopwareAG/shopware-4/blob/master/engine/Shopware/Components/Api/Resource/Article.php#L1371) clears all the stuff but then it just returns, no image ever gets assigned to an article. Is that intentional?
   I replaced it with

```
unset($data['images']);
$data['images'] = $images;
```

and that seems to fix my issues.

I can now upload and assign images while creating an article, in only one API request. Hooray, nice stuff, Shopware!

**Comment by bcremer** [comment]
Hi @nyov.
Thank's for your input. I'll take a closer look into this issue for the 4.2 release.
The 4.2 Release targets a lot of API-Improvements btw.

**Comment by dnoegel** [comment]
Hi,

thanks for opening this issue. In order to have all issues at one place, we've decided to move the GitHub issues to our own bug tracker which can be found at http://jira.shopware.de.

Your ticket can be found at the following url:

http://jira.shopware.de/?ticket=sw-6985
