### ISSUE TITLE
API duplicate article name/sku error should return existing article id

### ISSUE THREAD

**Issue by nyov** [shopware5/shopware#94]
The error message when trying to insert a duplicate Article reads something like `Errormesage: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'sku123' for key 'ordernumber'`.

At least in this instance the SQL error should be wrapped and the existing article's id returned instead, since otherwise it is impossible to run a workflow as
"try insert, on duplicate, update with returned id"
because Shopware's API only allows updates by id (not sku/name).

Currently the only possible way here is to fetch the whole product catalog and find the article name in the list, then get the id from there. This is not very nice with a big database and doing mass updates.

Alternatively, or additionally, since the sku/name is unique anyway, the option to allow updates by sku (as magento does) seems feasible.

Also quite useful would be supporting an 'upsert' operation equal to what mongodb has, which would allow to do an 'insert or update if exists' in a single network request.

**Comment by nyov** [comment]
I have made this work as in magento by accepting `id` or `sku` in `GET /api/articles/{id or sku}` and `PUT /api/articles/{id or sku}`. Which is good enough for me right now.

The changes were simple enough to figure out (for a non-php guy):
In [`engine/Shopware/Models/Article/Repository.php`](https://github.com/ShopwareAG/shopware-4/blob/master/engine/Shopware/Models/Article/Repository.php#L418) and [`engine/Shopware/Components/Api/Resource/Article.php`](https://github.com/ShopwareAG/shopware-4/blob/master/engine/Shopware/Components/Api/Resource/Article.php#L151)
replace

``` php
->where('article.id = ?1')
```

with

``` php
->where('article.id = ?1 OR mainDetail.number = ?1')
```

Maybe

``` php
->where('article.id = ?1')
->orWhere('mainDetail.number = ?1')
->andWhere('images.parentId IS NULL')
```

would be ok, too, but I don't know doctrine enough to figure if AND or OR would have preference then.
And what this does for query performance I can't say either... :p

(Now if I get a duplicate key error, I know the sku exists and can just run an update using that, without trying to figure out article id first.)

**Comment by dnoegel** [comment]
Hi @nyov,

what about the updateByNumber method? You can use this method by passing "?useNumberAsId=1" with your request to the REST interface. Shopware will then use the (order)number of the product to identify it.  So from my point of view your code snippet does not add new functionality - or did you mean something else?

**Comment by nyov** [comment]
Well... that one I didn't know. Talk about wasted effort :)
(ok I found the function in the code, but had no idea what 'use number' means, now that I know this field is "ordernumber" in the database it makes sense, vs. "name" in the API response, vs. "sku" in magento)

I'll close this, since this is indeed what I was looking for, but
maybe the feature should be documented in the Shopware4 API pages maybe?

Thanks
