### ISSUE TITLE
Its possible to create empty and double propertyGroups

### ISSUE THREAD

**Issue by Olli** [shopware5/shopware#97]
It's possible to create a empty propertyGroup. 
Also it's possible to create double property groups. This has no advantage in practical all day usability which means it should denied by SQL schema to create double groups. It also have advantages if there comes a POST on the REST API.

**Comment by dnoegel** [comment]
Hi,

thanks for opening this issue. In order to have all issues at one place, we've decided to move the GitHub issues to our own bug tracker which can be found at http://jira.shopware.de.

Your ticket can be found at the following url:

http://jira.shopware.de/?ticket=sw-6984
